# Generated by Django 3.2 on 2021-04-30 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_signup',
            name='name',
        ),
    ]
