# Generated by Django 3.2 on 2021-05-10 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0003_alter_user_signup_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_signup',
            name='image',
            field=models.ImageField(null=True, upload_to='profile_photo/'),
        ),
    ]
