# Generated by Django 3.2 on 2021-04-30 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='end_time',
            field=models.TimeField(default='04:38:20'),
        ),
        migrations.AlterField(
            model_name='book',
            name='start_time',
            field=models.TimeField(default='04:38:20'),
        ),
        migrations.AlterField(
            model_name='location',
            name='location_address',
            field=models.TextField(),
        ),
    ]
