# Generated by Django 3.2 on 2021-05-14 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0019_auto_20210511_0444'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='location_link',
            field=models.CharField(max_length=800, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='end_time',
            field=models.TimeField(default='03:11:08'),
        ),
        migrations.AlterField(
            model_name='book',
            name='start_time',
            field=models.TimeField(default='03:11:08'),
        ),
    ]
