# Generated by Django 3.2.6 on 2021-08-18 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0022_auto_20210517_2335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='end_time',
            field=models.TimeField(default='14:02:23'),
        ),
        migrations.AlterField(
            model_name='book',
            name='start_time',
            field=models.TimeField(default='14:02:23'),
        ),
    ]
