# Generated by Django 3.2 on 2021-04-30 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gateway', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='tag_number',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='time',
            field=models.TimeField(default='03:05:42'),
        ),
    ]
