# Generated by Django 3.2 on 2021-05-09 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gateway', '0009_alter_entry_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='time',
            field=models.TimeField(default='02:17:02'),
        ),
    ]
