# Generated by Django 3.2 on 2021-05-09 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0009_auto_20210510_0303'),
        ('gateway', '0010_alter_entry_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.location'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='time',
            field=models.TimeField(default='03:03:39'),
        ),
    ]
