# Generated by Django 3.2 on 2021-05-10 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gateway', '0011_auto_20210510_0303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='time',
            field=models.TimeField(default='23:48:52'),
        ),
    ]
