# Generated by Django 3.2.6 on 2021-08-18 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gateway', '0024_alter_entry_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='time',
            field=models.TimeField(default='14:02:23'),
        ),
    ]
